@url = http://localhost:5000/api

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTNlMWE4NmRkOTMwODJkOWNlN2E4NmIiLCJpYXQiOjE2MzE0NjExMzQsImV4cCI6MTYzMTU0NzUzNH0.auTSB4ySGmCRoeEdd9ZozAXbLrEkj1h-xrZ17ySZOPM

### User Registration ###
POST {{url}}/citizen/user/signup
Content-Type: application/json

{
    "username" : "Jaysonlods",
    "firstName" : "jayson",
    "lastName" : "leal",
    "email" : "jay.leal@gmails.com",
    "mobileNumber" : "654654654645",
    "language" : "religion",
    "yellowCardControlNumber" : "4234324324",
    "password" : "12345678",
    "religion" : "Roman Catholic"
 

}

### User Signin ###
POST {{url}}/citizen/user/signin
Content-Type: application/json

{
   "username" : "Jaysonlods", 
   "password" : "12345678"
}


### User signout ##
GET {{url}}/citizen/user/signout
Content-Type: application/json

{
   "Token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTE3OGU5ZTdmMTRjMDA5MTg5MWQ1ODciLCJpYXQiOjE2Mjg5MzM4OTQsImV4cCI6MTYyOTAyMDI5NH0.T4XDnitpti2db6w_Y7bbgVYcUvRB80SUBg1eTKhoIVI"
}

### Get Wallet ###
POST {{url}}/citizen/user/er
Authorization: Bearer {{token}}
Content-Type: application/json

{   
    "emergencyCategory" : "Red",
    "citizenId": "613e1a86dd93082d9ce7a86b",
    "typeOfEmergency" : "Life urgency",
    "emergencyAddress" : "Cash and carry mall makati",
    "userPhotoTaken" : ""
}

### Request wallet load ###
GET {{url}}/citizen/profile/613e1a86dd93082d9ce7a86b
Authorization: Bearer {{token}}

### USER PROFILE ###
PUT {{url}}/citizen/update-profile/613e1a86dd93082d9ce7a86b
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "username": "jaysonlods",
  "firstName": "jayson 2",
  "lastName": "leal",
  "email": "jay.leal@gmails.com",
  "language": "religion",
  "religion": "Roman Catholic",
  "yellowCardControlNumber": "4234324324",
  "mobileNumber": "654654654645"
}